In [46]:
# Transportation Operations & Performance Analytics
#
# Project Objective
# Analyze U.S. airline operations data to identify performance bottlenecks,
# major delay drivers, and opportunities for operational improvement.

In [ ]:
import pandas as pd

file_path = "../data/raw/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv"

df = pd.read_csv(file_path, low_memory=False)

print(df.shape)

/var/folders/2n/t3vdnyps4h56pf165b741t7w0000gn/T/ipykernel_99536/2431414611.py:5: DtypeWarning: Columns (0: Div1TailNum, 1: Div2Airport, 2: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

(539747, 110)

In [2]:
# Check the available columns before selecting the variables needed for analysis.

df.columns.tolist()

['Year',
 'Quarter',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'FlightDate',
 'Reporting_Airline',
 'DOT_ID_Reporting_Airline',
 'IATA_CODE_Reporting_Airline',
 'Tail_Number',
 'Flight_Number_Reporting_Airline',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'Origin',
 'OriginCityName',
 'OriginState',
 'OriginStateFips',
 'OriginStateName',
 'OriginWac',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'Dest',
 'DestCityName',
 'DestState',
 'DestStateFips',
 'DestStateName',
 'DestWac',
 'CRSDepTime',
 'DepTime',
 'DepDelay',
 'DepDelayMinutes',
 'DepDel15',
 'DepartureDelayGroups',
 'DepTimeBlk',
 'TaxiOut',
 'WheelsOff',
 'WheelsOn',
 'TaxiIn',
 'CRSArrTime',
 'ArrTime',
 'ArrDelay',
 'ArrDelayMinutes',
 'ArrDel15',
 'ArrivalDelayGroups',
 'ArrTimeBlk',
 'Cancelled',
 'CancellationCode',
 'Diverted',
 'CRSElapsedTime',
 'ActualElapsedTime',
 'AirTime',
 'Flights',
 'Distance',
 'DistanceGroup',
 'CarrierDelay',
 'WeatherDelay',
 'NASDelay',
 'SecurityDelay',
 'LateAircraftDelay',
 'FirstDepTime',
 'TotalAddGTime',
 'LongestAddGTime',
 'DivAirportLandings',
 'DivReachedDest',
 'DivActualElapsedTime',
 'DivArrDelay',
 'DivDistance',
 'Div1Airport',
 'Div1AirportID',
 'Div1AirportSeqID',
 'Div1WheelsOn',
 'Div1TotalGTime',
 'Div1LongestGTime',
 'Div1WheelsOff',
 'Div1TailNum',
 'Div2Airport',
 'Div2AirportID',
 'Div2AirportSeqID',
 'Div2WheelsOn',
 'Div2TotalGTime',
 'Div2LongestGTime',
 'Div2WheelsOff',
 'Div2TailNum',
 'Div3Airport',
 'Div3AirportID',
 'Div3AirportSeqID',
 'Div3WheelsOn',
 'Div3TotalGTime',
 'Div3LongestGTime',
 'Div3WheelsOff',
 'Div3TailNum',
 'Div4Airport',
 'Div4AirportID',
 'Div4AirportSeqID',
 'Div4WheelsOn',
 'Div4TotalGTime',
 'Div4LongestGTime',
 'Div4WheelsOff',
 'Div4TailNum',
 'Div5Airport',
 'Div5AirportID',
 'Div5AirportSeqID',
 'Div5WheelsOn',
 'Div5TotalGTime',
 'Div5LongestGTime',
 'Div5WheelsOff',
 'Div5TailNum',
 'Unnamed: 109']

In [3]:
# Review the dataset structure and data types.

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 539747 entries, 0 to 539746
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(21), str(19)
memory usage: 499.9 MB

In [4]:
# Take a first look at the raw flight data.

df.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,...,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2025,1,1,1,3,2025-01-01,AA,19805,AA,N104NN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025,1,1,2,4,2025-01-02,AA,19805,AA,N110AN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025,1,1,3,5,2025-01-03,AA,19805,AA,N106NN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025,1,1,4,6,2025-01-04,AA,19805,AA,N117AN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025,1,1,5,7,2025-01-05,AA,19805,AA,N104NN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Check a few key operational columns and their values.

df[["Origin", "Dest", "ArrTime", "ArrDelay", "Cancelled"]].head()

  Origin Dest  ArrTime  ArrDelay  Cancelled
0    JFK  LAX   1013.0      -7.0        0.0
1    JFK  LAX   1022.0       2.0        0.0
2    JFK  LAX   1003.0     -17.0        0.0
3    JFK  LAX   1016.0     -10.0        0.0
4    JFK  LAX   1013.0      -7.0        0.0

In [6]:
# Select the columns that are relevant to flight operations, delays,
# cancellations, and later analysis.

selected_columns = [
    "Year", "Quarter", "Month", "DayofMonth", "DayOfWeek", "FlightDate",
    "Reporting_Airline",
    "Origin", "OriginCityName", "OriginState",
    "Dest", "DestCityName", "DestState",
    "CRSDepTime", "DepTime", "DepDelay", "DepDelayMinutes", "DepDel15", "DepTimeBlk", "TaxiOut",
    "CRSArrTime", "ArrTime", "ArrDelay", "ArrDelayMinutes", "ArrDel15", "ArrTimeBlk", "TaxiIn",
    "Cancelled", "CancellationCode", "Diverted",
    "AirTime", "Distance",
    "CarrierDelay", "WeatherDelay", "NASDelay", "SecurityDelay", "LateAircraftDelay"
]

df[selected_columns].head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,Origin,OriginCityName,OriginState,...,Cancelled,CancellationCode,Diverted,AirTime,Distance,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2025,1,1,1,3,2025-01-01,AA,JFK,"New York, NY",NY,...,0.0,NaN,0.0,345.0,2475.0,NaN,NaN,NaN,NaN,NaN
1,2025,1,1,2,4,2025-01-02,AA,JFK,"New York, NY",NY,...,0.0,NaN,0.0,353.0,2475.0,NaN,NaN,NaN,NaN,NaN
2,2025,1,1,3,5,2025-01-03,AA,JFK,"New York, NY",NY,...,0.0,NaN,0.0,347.0,2475.0,NaN,NaN,NaN,NaN,NaN
3,2025,1,1,4,6,2025-01-04,AA,JFK,"New York, NY",NY,...,0.0,NaN,0.0,349.0,2475.0,NaN,NaN,NaN,NaN,NaN
4,2025,1,1,5,7,2025-01-05,AA,JFK,"New York, NY",NY,...,0.0,NaN,0.0,347.0,2475.0,NaN,NaN,NaN,NaN,NaN

In [7]:
# Check missing values before cleaning the data.

df.isna().sum()

Year                     0
Quarter                  0
Month                    0
DayofMonth               0
DayOfWeek                0
                     ...
Div5TotalGTime      539747
Div5LongestGTime    539747
Div5WheelsOff       539747
Div5TailNum         539747
Unnamed: 109        539747
Length: 110, dtype: int64

In [8]:
# Check missing values only for the columns selected for analysis.

df[selected_columns].isna().sum()

Year                      0
Quarter                   0
Month                     0
DayofMonth                0
DayOfWeek                 0
FlightDate                0
Reporting_Airline         0
Origin                    0
OriginCityName            0
OriginState               0
Dest                      0
DestCityName              0
DestState                 0
CRSDepTime                0
DepTime               15886
DepDelay              15923
DepDelayMinutes       15923
DepDel15              15923
DepTimeBlk                0
TaxiOut               16227
CRSArrTime                0
ArrTime               16580
ArrDelay              17478
ArrDelayMinutes       17478
ArrDel15              17478
ArrTimeBlk                0
TaxiIn                16580
Cancelled                 0
CancellationCode     523435
Diverted                  0
AirTime               17478
Distance                  0
CarrierDelay         441617
WeatherDelay         441617
NASDelay             441617
SecurityDelay        441617
LateAircraftDelay    441617
dtype: int64

In [9]:
# Check how many flights were cancelled.

df["Cancelled"].value_counts(dropna=False)

Cancelled
0.0    523435
1.0     16312
Name: count, dtype: int64

In [10]:
# Compare cancellation status with missing arrival delay values.
# This helps determine whether missing ArrDelay values are expected.

pd.crosstab(df["Cancelled"],df["ArrDelay"].isna())

ArrDelay    False  True
Cancelled
0.0        522269   1166
1.0             0  16312

In [11]:
# Check whether flights with missing ArrDelay are cancelled or diverted.

df[(df["Cancelled"]== 0) & (df["ArrDelay"].isna())] [["FlightDate", "Reporting_Airline", "Origin", "Dest",
     "DepTime", "ArrTime", "ArrDelay", "Diverted"]].head(20)

,FlightDate,Reporting_Airline,Origin,Dest,DepTime,ArrTime,ArrDelay,Diverted
53,2025-01-23,AA,LAX,JFK,655.0,1818.0,NaN,1.0
119,2025-01-01,AA,ORD,MSY,1026.0,1520.0,NaN,1.0
224,2025-01-19,AA,SFO,JFK,1237.0,150.0,NaN,1.0
489,2025-01-12,AA,LAX,JFK,605.0,1456.0,NaN,1.0
729,2025-01-08,AA,JFK,LAX,556.0,1151.0,NaN,1.0
815,2025-01-04,AA,ORD,DFW,2013.0,1416.0,NaN,1.0
887,2025-01-19,AA,LAX,JFK,1129.0,136.0,NaN,1.0
1310,2025-01-06,AA,JFK,EGE,737.0,1530.0,NaN,1.0
1483,2025-01-23,AA,LAX,MIA,610.0,1933.0,NaN,1.0
1658,2025-01-26,AA,IAH,MIA,528.0,1514.0,NaN,1.0
4752,2025-01-29,AA,DFW,DCA,1706.0,NaN,NaN,1.0
4835,2025-01-19,AA,PHX,PHL,1731.0,1019.0,NaN,1.0
5135,2025-01-23,AA,DCA,MIA,1006.0,1006.0,NaN,1.0
5525,2025-01-19,AA,LAX,PHL,1541.0,1219.0,NaN,1.0
5732,2025-01-11,AA,ORD,DCA,712.0,2122.0,NaN,1.0
5881,2025-01-05,AA,CHS,DFW,756.0,1242.0,NaN,1.0
6417,2025-01-09,AA,LGA,DFW,845.0,1850.0,NaN,1.0
6530,2025-01-19,AA,MCO,PHL,2030.0,724.0,NaN,1.0
6708,2025-01-25,AA,CLT,SDF,2256.0,210.0,NaN,1.0
6745,2025-01-06,AA,DFW,CLE,2139.0,407.0,NaN,1.0

In [12]:
# Data Quality Finding
# Missing `ArrDelay` values are mainly associated with cancelled or diverted flights.
# Cancelled flights do not have a normal arrival, while diverted flights are handled separately.

In [13]:
# Check for duplicate rows.

df.duplicated().sum()

np.int64(0)

In [14]:
# Review the distribution of several numeric operational variables.

df[["DepDelay", "ArrDelay", "Distance", "TaxiOut", "TaxiIn"]].describe()

,DepDelay,ArrDelay,Distance,TaxiOut,TaxiIn
count,523824.000000,522269.000000,539747.000000,523520.000000,523167.000000
mean,10.340809,3.756614,843.208216,19.057864,8.322583
std,54.328344,56.850884,599.092323,11.230402,6.801095
min,-50.000000,-87.000000,31.000000,1.000000,1.000000
25%,-6.000000,-18.000000,403.000000,12.000000,5.000000
50%,-3.000000,-8.000000,701.000000,16.000000,6.000000
75%,6.000000,7.000000,1083.000000,22.000000,10.000000
max,3298.000000,3282.000000,5095.000000,182.000000,212.000000

In [15]:
# Check how many flights were neither cancelled nor diverted.
# These flights are the main candidates for the operational delay analysis.

df[(df["Cancelled"] == 0) & (df["Diverted"] == 0)].shape

(522269, 110)

In [16]:
# Keep only flights that were not cancelled and were not diverted.
# These flights have a normal departure and arrival and are more appropriate
# for the main delay analysis.


df_analysis = df[(df["Cancelled"] == 0) & (df["Diverted"] == 0)].copy()

In [17]:
# Check the number of rows after removing cancelled and diverted flights.

df_analysis.shape

(522269, 110)

In [18]:
# Review the available columns in the filtered dataset.

df_analysis.columns.tolist()

['Year',
 'Quarter',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'FlightDate',
 'Reporting_Airline',
 'DOT_ID_Reporting_Airline',
 'IATA_CODE_Reporting_Airline',
 'Tail_Number',
 'Flight_Number_Reporting_Airline',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'Origin',
 'OriginCityName',
 'OriginState',
 'OriginStateFips',
 'OriginStateName',
 'OriginWac',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'Dest',
 'DestCityName',
 'DestState',
 'DestStateFips',
 'DestStateName',
 'DestWac',
 'CRSDepTime',
 'DepTime',
 'DepDelay',
 'DepDelayMinutes',
 'DepDel15',
 'DepartureDelayGroups',
 'DepTimeBlk',
 'TaxiOut',
 'WheelsOff',
 'WheelsOn',
 'TaxiIn',
 'CRSArrTime',
 'ArrTime',
 'ArrDelay',
 'ArrDelayMinutes',
 'ArrDel15',
 'ArrivalDelayGroups',
 'ArrTimeBlk',
 'Cancelled',
 'CancellationCode',
 'Diverted',
 'CRSElapsedTime',
 'ActualElapsedTime',
 'AirTime',
 'Flights',
 'Distance',
 'DistanceGroup',
 'CarrierDelay',
 'WeatherDelay',
 'NASDelay',
 'SecurityDelay',
 'LateAircraftDelay',
 'FirstDepTime',
 'TotalAddGTime',
 'LongestAddGTime',
 'DivAirportLandings',
 'DivReachedDest',
 'DivActualElapsedTime',
 'DivArrDelay',
 'DivDistance',
 'Div1Airport',
 'Div1AirportID',
 'Div1AirportSeqID',
 'Div1WheelsOn',
 'Div1TotalGTime',
 'Div1LongestGTime',
 'Div1WheelsOff',
 'Div1TailNum',
 'Div2Airport',
 'Div2AirportID',
 'Div2AirportSeqID',
 'Div2WheelsOn',
 'Div2TotalGTime',
 'Div2LongestGTime',
 'Div2WheelsOff',
 'Div2TailNum',
 'Div3Airport',
 'Div3AirportID',
 'Div3AirportSeqID',
 'Div3WheelsOn',
 'Div3TotalGTime',
 'Div3LongestGTime',
 'Div3WheelsOff',
 'Div3TailNum',
 'Div4Airport',
 'Div4AirportID',
 'Div4AirportSeqID',
 'Div4WheelsOn',
 'Div4TotalGTime',
 'Div4LongestGTime',
 'Div4WheelsOff',
 'Div4TailNum',
 'Div5Airport',
 'Div5AirportID',
 'Div5AirportSeqID',
 'Div5WheelsOn',
 'Div5TotalGTime',
 'Div5LongestGTime',
 'Div5WheelsOff',
 'Div5TailNum',
 'Unnamed: 109']

In [19]:
# Select the variables needed for the final cleaned dataset and analysis.

selected_columns = [
    "FlightDate",
    "Year",
    "Month",
    "DayOfWeek",
    "Reporting_Airline",
    "Origin",
    "OriginCityName",
    "OriginState",
    "Dest",
    "DestCityName",
    "DestState",
    "CRSDepTime",
    "DepTime",
    "DepDelay",
    "DepDelayMinutes",
    "DepDel15",
    "DepTimeBlk",
    "TaxiOut",
    "CRSArrTime",
    "ArrTime",
    "ArrDelay",
    "ArrDelayMinutes",
    "ArrDel15",
    "ArrTimeBlk",
    "TaxiIn",
    "AirTime",
    "Distance",
    "CarrierDelay",
    "WeatherDelay",
    "NASDelay",
    "SecurityDelay",
    "LateAircraftDelay"
]

df_clean = df_analysis[selected_columns].copy()

In [20]:
# Check the shape of the cleaned dataset.

df_clean.shape

(522269, 32)

In [21]:
# Check the data types before making any transformations.

df_clean.dtypes

FlightDate               str
Year                   int64
Month                  int64
DayOfWeek              int64
Reporting_Airline        str
Origin                   str
OriginCityName           str
OriginState              str
Dest                     str
DestCityName             str
DestState                str
CRSDepTime             int64
DepTime              float64
DepDelay             float64
DepDelayMinutes      float64
DepDel15             float64
DepTimeBlk               str
TaxiOut              float64
CRSArrTime             int64
ArrTime              float64
ArrDelay             float64
ArrDelayMinutes      float64
ArrDel15             float64
ArrTimeBlk               str
TaxiIn               float64
AirTime              float64
Distance             float64
CarrierDelay         float64
WeatherDelay         float64
NASDelay             float64
SecurityDelay        float64
LateAircraftDelay    float64
dtype: object

In [22]:
# Convert FlightDate to datetime so it can be used consistently
# for date-based analysis.

df_clean["FlightDate"] = pd.to_datetime(df_clean["FlightDate"])

df_clean["FlightDate"].dtype

dtype('<M8[us]')

In [23]:
# Review the distribution of scheduled and actual departure and arrival times.

df_clean[["CRSDepTime", "DepTime", "CRSArrTime", "ArrTime"]].describe()

          CRSDepTime        DepTime     CRSArrTime        ArrTime
count  522269.000000  522269.000000  522269.000000  522269.000000
mean     1315.261628    1320.672393    1502.718465    1482.530569
std       479.664906     491.794270     501.501217     519.818247
min         5.000000       1.000000       1.000000       1.000000
25%       905.000000     911.000000    1118.000000    1106.000000
50%      1310.000000    1318.000000    1524.000000    1515.000000
75%      1724.000000    1731.000000    1922.000000    1917.000000
max      2359.000000    2400.000000    2359.000000    2400.000000

In [24]:
# Time Feature
# `DepTimeBlk` is provided by BTS as an hourly departure-time block. 
# We also created `DepHour` from `CRSDepTime` to make hour-level analysis easier.

df_clean["DepHour"] = df_clean["CRSDepTime"] // 100

df_clean["DepHour"].head()

0    6
1    6
2    6
3    7
4    6
Name: DepHour, dtype: int64

In [25]:
# Check the number of flights in each scheduled departure hour.

df_clean["DepHour"].value_counts().sort_index()

DepHour
0       564
1       282
2        93
3        55
4        25
5     13411
6     35230
7     36580
8     37650
9     31326
10    32059
11    34881
12    32004
13    31831
14    31835
15    30824
16    30894
17    33839
18    32430
19    26163
20    22326
21    14662
22     9671
23     3634
Name: count, dtype: int64

In [26]:
# Create a route identifier using the origin and destination airport codes.
# This will be used for route-level analysis.

df_clean["Route"] = df_clean["Origin"] + "-" + df_clean["Dest"]

df_clean["Route"].nunique()

5645

In [27]:
# Check the minimum and maximum values of the new departure-hour feature.

df_clean["DepHour"].min(), df_clean["DepHour"].max()

(np.int64(0), np.int64(23))

In [28]:
# Check whether any route values are missing.

df_clean["Route"].isna().sum()

np.int64(0)

In [29]:
# Review the new time and route features.

df_clean[["FlightDate", "CRSDepTime", "DepHour", "Origin", "Dest", "Route"]].head(10)

  FlightDate  CRSDepTime  DepHour Origin Dest    Route
0 2025-01-01         659        6    JFK  LAX  JFK-LAX
1 2025-01-02         659        6    JFK  LAX  JFK-LAX
2 2025-01-03         659        6    JFK  LAX  JFK-LAX
3 2025-01-04         700        7    JFK  LAX  JFK-LAX
4 2025-01-05         659        6    JFK  LAX  JFK-LAX
5 2025-01-06         659        6    JFK  LAX  JFK-LAX
6 2025-01-07         700        7    JFK  LAX  JFK-LAX
7 2025-01-08         700        7    JFK  LAX  JFK-LAX
8 2025-01-09         659        6    JFK  LAX  JFK-LAX
9 2025-01-10         700        7    JFK  LAX  JFK-LAX

In [30]:
from pathlib import Path

# Find all monthly raw CSV files so the complete 2025 dataset can be combined.

raw_files = sorted(Path("../data/raw").glob("*.csv"))

print("number of csv files", len(raw_files))

for file in raw_files:
    print(file.name)

number of csv files 12
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_10.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_11.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_12.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_2.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_3.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_4.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_5.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_6.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_7.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_8.csv
On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_9.csv

In [31]:
# Read the required columns from each monthly file.
# Only the selected variables are loaded to reduce unnecessary memory usage.

monthly_data = []

for file in raw_files:
    print("Reading:", file.name)

    monthly_df = pd.read_csv(
        file,
        usecols=selected_columns + ["Cancelled", "Diverted"],
        low_memory=False
    )

    monthly_data.append(monthly_df)

    print("Rows:", len(monthly_df))

Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_1.csv
Rows: 539747
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_10.csv
Rows: 605844
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_11.csv
Rows: 570550
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_12.csv
Rows: 582304
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_2.csv
Rows: 504884
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_3.csv
Rows: 600872
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_4.csv
Rows: 583950
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_5.csv
Rows: 605648
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_6.csv
Rows: 611575
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_7.csv
Rows: 631428
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_8.csv
Rows: 602378
Reading: On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2025_9.csv
Rows: 562439

In [32]:
# Combine all monthly files into a single 2025 dataset

df_2025= pd.concat(monthly_data, ignore_index=True)

print(df_2025.shape)

(7001619, 34)

In [33]:
# Remove cancelled and diverted flights from the complete 2025 dataset
# so the final analysis focuses on flights with normal operations.

df_analysis = df_2025[(df_2025["Cancelled"] == 0) & (df_2025["Diverted"] == 0)].copy()

print(df_analysis.shape)

(6879485, 34)

In [34]:
# Create the final cleaned dataset using the selected analysis columns.

df_clean = df_analysis[selected_columns].copy()

df_clean.shape

(6879485, 32)

In [35]:
# Check the data types of the final cleaned dataset.

df_clean.dtypes

FlightDate               str
Year                   int64
Month                  int64
DayOfWeek              int64
Reporting_Airline        str
Origin                   str
OriginCityName           str
OriginState              str
Dest                     str
DestCityName             str
DestState                str
CRSDepTime             int64
DepTime              float64
DepDelay             float64
DepDelayMinutes      float64
DepDel15             float64
DepTimeBlk               str
TaxiOut              float64
CRSArrTime             int64
ArrTime              float64
ArrDelay             float64
ArrDelayMinutes      float64
ArrDel15             float64
ArrTimeBlk               str
TaxiIn               float64
AirTime              float64
Distance             float64
CarrierDelay         float64
WeatherDelay         float64
NASDelay             float64
SecurityDelay        float64
LateAircraftDelay    float64
dtype: object

In [36]:
# Convert FlightDate to datetime in the complete 2025 dataset.

df_clean["FlightDate"] = pd.to_datetime(df_clean["FlightDate"])

df_clean["FlightDate"].dtype

dtype('<M8[us]')

In [37]:
# Review the distribution of scheduled and actual departure and arrival times
# after combining the full 2025 dataset.

df_clean[["CRSDepTime", "DepTime", "CRSArrTime", "ArrTime"]].describe()

         CRSDepTime       DepTime    CRSArrTime       ArrTime
count  6.879485e+06  6.879485e+06  6.879485e+06  6.879484e+06
mean   1.322206e+03  1.327854e+03  1.490769e+03  1.459793e+03
std    4.918457e+02  5.110587e+02  5.180303e+02  5.484875e+02
min    1.000000e+00  1.000000e+00  1.000000e+00  1.000000e+00
25%    9.020000e+02  9.040000e+02  1.102000e+03  1.042000e+03
50%    1.315000e+03  1.322000e+03  1.516000e+03  1.502000e+03
75%    1.733000e+03  1.745000e+03  1.925000e+03  1.920000e+03
max    2.400000e+03  2.400000e+03  2.400000e+03  2.400000e+03

In [38]:
# Time Feature
# DepTimeBlk is provided by BTS as an hourly departure-time block.
# We also create DepHour from CRSDepTime to make hour-level analysis easier.

df_clean["DepHour"] = df_clean["CRSDepTime"] // 100

df_clean["DepHour"].head()

0    6
1    6
2    6
3    7
4    6
Name: DepHour, dtype: int64

In [39]:
# Check the distribution of flights across departure hours.

df_clean["DepHour"].value_counts().sort_index()

DepHour
0      11075
1       3393
2       1299
3        732
4        298
5     194931
6     474704
7     501217
8     478909
9     390739
10    427414
11    431894
12    408052
13    410959
14    397468
15    394967
16    394921
17    432324
18    408988
19    373468
20    303871
21    229222
22    153112
23     55527
24         1
Name: count, dtype: int64

In [40]:
# Create the route identifier for the complete 2025 dataset.

df_clean["Route"] = df_clean["Origin"] + "-" + df_clean["Dest"]

df_clean["Route"].nunique()

6927

In [41]:
# Check the range of the departure-hour feature.

df_clean["DepHour"].min(), df_clean["DepHour"].max()

(np.int64(0), np.int64(24))

In [42]:
# Confirm that the route feature does not contain missing values.

df_clean["Route"].isna().sum()

np.int64(0)

In [43]:
# Review the final time and route features.

df_clean[["FlightDate", "CRSDepTime", "DepHour", "Origin", "Dest", "Route"]].head(10)

  FlightDate  CRSDepTime  DepHour Origin Dest    Route
0 2025-01-01         659        6    JFK  LAX  JFK-LAX
1 2025-01-02         659        6    JFK  LAX  JFK-LAX
2 2025-01-03         659        6    JFK  LAX  JFK-LAX
3 2025-01-04         700        7    JFK  LAX  JFK-LAX
4 2025-01-05         659        6    JFK  LAX  JFK-LAX
5 2025-01-06         659        6    JFK  LAX  JFK-LAX
6 2025-01-07         700        7    JFK  LAX  JFK-LAX
7 2025-01-08         700        7    JFK  LAX  JFK-LAX
8 2025-01-09         659        6    JFK  LAX  JFK-LAX
9 2025-01-10         700        7    JFK  LAX  JFK-LAX

In [44]:
# Save the final cleaned dataset as a CSV file for use in later analysis
# and other tools.

df_clean.to_csv(Path("../data/processed")/"transportation_2025_clean.csv", index=False)

In [45]:
# The CSV file is relatively large, so save the same cleaned dataset
# in Parquet format as a more compact data structure.

df_clean.to_parquet("../Data/Processed/transportation_2025_clean.parquet",index=False)